from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from prompt2model.config import PipelineConfig


def format_duration(seconds: float) -> str:
    """Formats seconds as HH:MM:SS or MM:SS."""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    if h > 0:
        return f"{h:02d}h {m:02d}m {s:02d}s"
    return f"{m:02d}m {s:02d}s"


def write_markdown_report(
    output_path: str | Path,
    config: PipelineConfig,
    metrics: dict[str, Any],
    training_history: list[dict[str, float]],
    export_path: str | None,
    hpo_results: Any | None = None,
    telemetry: dict[str, Any] | None = None,
) -> str:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    elapsed = telemetry.get("total_time_seconds", 0) if telemetry else 0
    time_str = format_duration(elapsed)
    
    lines = [
        "# 🚀 Prompt2Model Evaluation Report",
        "",
        "## 📝 Prompt & Task Summary",
        f"> \"{config.prompt}\"",
        "",
        f"- **Task Type**: `{config.task.value.upper()}`",
        f"- **Model**: `{config.model_name}`",
        f"- **Dataset**: `{config.dataset.root}`",
        f"- **Augmentations**: `{', '.join(config.augmentation_tags) or 'none'}`",
        "",
        "## 🔍 Resource & Timing Analysis",
        f"- **Total Training Time**: `{time_str}`",
        f"- **HPO Trials Completed**: `{getattr(hpo_results, 'n_trials_completed', 0)}`",
        f"- **Training Device**: `{telemetry.get('device', 'unknown') if telemetry else 'unknown'}`",
        "",
        "## 🏷️ Resolved Labels",
    ]
    for resolved in config.resolved_labels:
        lines.append(
            f"- `{resolved.requested_label}` → `{resolved.dataset_label}` "
            f"(method: **{resolved.method}**, score: `{resolved.score:.3f}`)"
        )
    lines.extend(
        [
            "",
            "## 📈 Metrics",
            "```json",
            json.dumps(metrics, indent=2),
            "```",
            "",
            "## 📦 Export Information",
            f"- ONNX Model Path: `{export_path or 'Not exported'}`",
            "",
            "---",
            "*Report generated by Prompt2Model Hardware-Accelerated Factory*",
        ]
    )
    output_path.write_text("\n".join(lines))
    return str(output_path)

